version: '3'
services:
  db:
      image: mongo:6
      container_name: mongo-chatter
      restart: always
      ports:
        - 27022:27017
      environment:
        MONGODB_DATABASE: chatter
      volumes:
        - ./mongo:/data/db
      networks:
      - app-network
networks:
  app-network:
    driver: bridge
